import { Sure } from "../../types/quran/sureType";

export const SURE_LIST: Sure[] = [
  { sira: 1, sureAdi: "Fâtiha", sureAdiArapca: "الفاتحة", ayetSayisi: 7 },
  { sira: 2, sureAdi: "Bakara", sureAdiArapca: "البقرة", ayetSayisi: 286 },
  { sira: 3, sureAdi: "Âl-i İmrân", sureAdiArapca: "آل عمران", ayetSayisi: 200 },
  { sira: 4, sureAdi: "Nisâ", sureAdiArapca: "النساء", ayetSayisi: 176 },
  { sira: 5, sureAdi: "Mâide", sureAdiArapca: "المائدة", ayetSayisi: 120 },
  { sira: 6, sureAdi: "En'âm", sureAdiArapca: "الأنعام", ayetSayisi: 165 },
  { sira: 7, sureAdi: "A'râf", sureAdiArapca: "الأعراف", ayetSayisi: 206 },
  { sira: 8, sureAdi: "Enfâl", sureAdiArapca: "الأنفال", ayetSayisi: 75 },
  { sira: 9, sureAdi: "Tevbe", sureAdiArapca: "التوبة", ayetSayisi: 129 },
  { sira: 10, sureAdi: "Yunus", sureAdiArapca: "يونس", ayetSayisi: 109 },
  { sira: 11, sureAdi: "Hûd", sureAdiArapca: "هود", ayetSayisi: 123 },
  { sira: 12, sureAdi: "Yusuf", sureAdiArapca: "يوسف", ayetSayisi: 111 },
  { sira: 13, sureAdi: "Ra'd", sureAdiArapca: "الرعد", ayetSayisi: 43 },
  { sira: 14, sureAdi: "İbrahim", sureAdiArapca: "إبراهيم", ayetSayisi: 52 },
  { sira: 15, sureAdi: "Hicr", sureAdiArapca: "الحجر", ayetSayisi: 99 },
  { sira: 16, sureAdi: "Nahl", sureAdiArapca: "النحل", ayetSayisi: 128 },
  { sira: 17, sureAdi: "İsrâ", sureAdiArapca: "الإسراء", ayetSayisi: 111 },
  { sira: 18, sureAdi: "Kehf", sureAdiArapca: "الكهف", ayetSayisi: 110 },
  { sira: 19, sureAdi: "Meryem", sureAdiArapca: "مريم", ayetSayisi: 98 },
  { sira: 20, sureAdi: "Tâ-Hâ", sureAdiArapca: "طه", ayetSayisi: 135 },
  { sira: 21, sureAdi: "Enbiyâ", sureAdiArapca: "الأنبياء", ayetSayisi: 112 },
  { sira: 22, sureAdi: "Hac", sureAdiArapca: "الحج", ayetSayisi: 78 },
  { sira: 23, sureAdi: "Mü'minûn", sureAdiArapca: "المؤمنون", ayetSayisi: 118 },
  { sira: 24, sureAdi: "Nûr", sureAdiArapca: "النور", ayetSayisi: 64 },
  { sira: 25, sureAdi: "Furkan", sureAdiArapca: "الفرقان", ayetSayisi: 77 },
  { sira: 26, sureAdi: "Şuarâ", sureAdiArapca: "الشعراء", ayetSayisi: 227 },
  { sira: 27, sureAdi: "Neml", sureAdiArapca: "النمل", ayetSayisi: 93 },
  { sira: 28, sureAdi: "Kasas", sureAdiArapca: "القصص", ayetSayisi: 88 },
  { sira: 29, sureAdi: "Ankebût", sureAdiArapca: "العنكبوت", ayetSayisi: 69 },
  { sira: 30, sureAdi: "Rûm", sureAdiArapca: "الروم", ayetSayisi: 60 },
  { sira: 31, sureAdi: "Lokman", sureAdiArapca: "لقمان", ayetSayisi: 34 },
  { sira: 32, sureAdi: "Secde", sureAdiArapca: "السجدة", ayetSayisi: 30 },
  { sira: 33, sureAdi: "Ahzâb", sureAdiArapca: "الأحزاب", ayetSayisi: 73 },
  { sira: 34, sureAdi: "Sebe'", sureAdiArapca: "سبأ", ayetSayisi: 54 },
  { sira: 35, sureAdi: "Fâtır", sureAdiArapca: "فاطر", ayetSayisi: 45 },
  { sira: 36, sureAdi: "Yâsin", sureAdiArapca: "يس", ayetSayisi: 83 },
  { sira: 37, sureAdi: "Sâffât", sureAdiArapca: "الصافات", ayetSayisi: 182 },
  { sira: 38, sureAdi: "Sâd", sureAdiArapca: "ص", ayetSayisi: 88 },
  { sira: 39, sureAdi: "Zümer", sureAdiArapca: "الزمر", ayetSayisi: 75 },
  { sira: 40, sureAdi: "Mü'min", sureAdiArapca: "غافر", ayetSayisi: 85 },
  { sira: 41, sureAdi: "Fussilet", sureAdiArapca: "فصلت", ayetSayisi: 54 },
  { sira: 42, sureAdi: "Şûrâ", sureAdiArapca: "الشورى", ayetSayisi: 53 },
  { sira: 43, sureAdi: "Zuhruf", sureAdiArapca: "الزخرف", ayetSayisi: 89 },
  { sira: 44, sureAdi: "Duhân", sureAdiArapca: "الدخان", ayetSayisi: 59 },
  { sira: 45, sureAdi: "Câsiye", sureAdiArapca: "الجاثية", ayetSayisi: 37 },
  { sira: 46, sureAdi: "Ahkaf", sureAdiArapca: "الأحقاف", ayetSayisi: 35 },
  { sira: 47, sureAdi: "Muhammed", sureAdiArapca: "محمد", ayetSayisi: 38 },
  { sira: 48, sureAdi: "Fetih", sureAdiArapca: "الفتح", ayetSayisi: 29 },
  { sira: 49, sureAdi: "Hucurât", sureAdiArapca: "الحجرات", ayetSayisi: 18 },
  { sira: 50, sureAdi: "Kaf", sureAdiArapca: "ق", ayetSayisi: 45 },
  { sira: 51, sureAdi: "Zâriyât", sureAdiArapca: "الذاريات", ayetSayisi: 60 },
  { sira: 52, sureAdi: "Tûr", sureAdiArapca: "الطور", ayetSayisi: 49 },
  { sira: 53, sureAdi: "Necm", sureAdiArapca: "النجم", ayetSayisi: 62 },
  { sira: 54, sureAdi: "Kamer", sureAdiArapca: "القمر", ayetSayisi: 55 },
  { sira: 55, sureAdi: "Rahmân", sureAdiArapca: "الرحمن", ayetSayisi: 78 },
  { sira: 56, sureAdi: "Vâkıa", sureAdiArapca: "الواقعة", ayetSayisi: 96 },
  { sira: 57, sureAdi: "Hadid", sureAdiArapca: "الحديد", ayetSayisi: 29 },
  { sira: 58, sureAdi: "Mücâdele", sureAdiArapca: "المجادلة", ayetSayisi: 22 },
  { sira: 59, sureAdi: "Haşr", sureAdiArapca: "الحشر", ayetSayisi: 24 },
  { sira: 60, sureAdi: "Mümtehine", sureAdiArapca: "الممتحنة", ayetSayisi: 13 },
  { sira: 61, sureAdi: "Saf", sureAdiArapca: "الصف", ayetSayisi: 14 },
  { sira: 62, sureAdi: "Cum'a", sureAdiArapca: "الجمعة", ayetSayisi: 11 },
  { sira: 63, sureAdi: "Münâfikûn", sureAdiArapca: "المنافقون", ayetSayisi: 11 },
  { sira: 64, sureAdi: "Teğabün", sureAdiArapca: "التغابن", ayetSayisi: 18 },
  { sira: 65, sureAdi: "Talâk", sureAdiArapca: "الطلاق", ayetSayisi: 12 },
  { sira: 66, sureAdi: "Tahrim", sureAdiArapca: "التحريم", ayetSayisi: 12 },
  { sira: 67, sureAdi: "Mülk", sureAdiArapca: "الملك", ayetSayisi: 30 },
  { sira: 68, sureAdi: "Kalem", sureAdiArapca: "القلم", ayetSayisi: 52 },
  { sira: 69, sureAdi: "Hâkka", sureAdiArapca: "الحاقة", ayetSayisi: 52 },
  { sira: 70, sureAdi: "Meâric", sureAdiArapca: "المعارج", ayetSayisi: 44 },
  { sira: 71, sureAdi: "Nuh", sureAdiArapca: "نوح", ayetSayisi: 28 },
  { sira: 72, sureAdi: "Cin", sureAdiArapca: "الجن", ayetSayisi: 28 },
  { sira: 73, sureAdi: "Müzzemmil", sureAdiArapca: "المزمل", ayetSayisi: 20 },
  { sira: 74, sureAdi: "Müddessir", sureAdiArapca: "المدثر", ayetSayisi: 56 },
  { sira: 75, sureAdi: "Kıyamet", sureAdiArapca: "القيامة", ayetSayisi: 40 },
  { sira: 76, sureAdi: "İnsan", sureAdiArapca: "الإنسان", ayetSayisi: 31 },
  { sira: 77, sureAdi: "Mürselât", sureAdiArapca: "المرسلات", ayetSayisi: 50 },
  { sira: 78, sureAdi: "Nebe'", sureAdiArapca: "النبأ", ayetSayisi: 40 },
  { sira: 79, sureAdi: "Nâziât", sureAdiArapca: "النازعات", ayetSayisi: 46 },
  { sira: 80, sureAdi: "Abese", sureAdiArapca: "عبس", ayetSayisi: 42 },
  { sira: 81, sureAdi: "Tekvir", sureAdiArapca: "التكوير", ayetSayisi: 29 },
  { sira: 82, sureAdi: "İnfitâr", sureAdiArapca: "الانفطار", ayetSayisi: 19 },
  { sira: 83, sureAdi: "Mutaffifin", sureAdiArapca: "المطففين", ayetSayisi: 36 },
  { sira: 84, sureAdi: "İnşikak", sureAdiArapca: "الانشقاق", ayetSayisi: 25 },
  { sira: 85, sureAdi: "Bürûc", sureAdiArapca: "البروج", ayetSayisi: 22 },
  { sira: 86, sureAdi: "Târık", sureAdiArapca: "الطارق", ayetSayisi: 17 },
  { sira: 87, sureAdi: "A'lâ", sureAdiArapca: "الأعلى", ayetSayisi: 19 },
  { sira: 88, sureAdi: "Gâşiye", sureAdiArapca: "الغاشية", ayetSayisi: 26 },
  { sira: 89, sureAdi: "Fecr", sureAdiArapca: "الفجر", ayetSayisi: 30 },
  { sira: 90, sureAdi: "Beled", sureAdiArapca: "البلد", ayetSayisi: 20 },
  { sira: 91, sureAdi: "Şems", sureAdiArapca: "الشمس", ayetSayisi: 15 },
  { sira: 92, sureAdi: "Leyl", sureAdiArapca: "الليل", ayetSayisi: 21 },
  { sira: 93, sureAdi: "Duhâ", sureAdiArapca: "الضحى", ayetSayisi: 11 },
  { sira: 94, sureAdi: "İnşirâh", sureAdiArapca: "الشرح", ayetSayisi: 8 },
  { sira: 95, sureAdi: "Tin", sureAdiArapca: "التين", ayetSayisi: 8 },
  { sira: 96, sureAdi: "Alak", sureAdiArapca: "العلق", ayetSayisi: 19 },
  { sira: 97, sureAdi: "Kadir", sureAdiArapca: "القدر", ayetSayisi: 5 },
  { sira: 98, sureAdi: "Beyyine", sureAdiArapca: "البينة", ayetSayisi: 8 },
  { sira: 99, sureAdi: "Zilzâl", sureAdiArapca: "الزلزلة", ayetSayisi: 8 },
  { sira: 100, sureAdi: "Âdiyât", sureAdiArapca: "العاديات", ayetSayisi: 11 },
  { sira: 101, sureAdi: "Kâria", sureAdiArapca: "القارعة", ayetSayisi: 11 },
  { sira: 102, sureAdi: "Tekâsür", sureAdiArapca: "التكاثر", ayetSayisi: 8 },
  { sira: 103, sureAdi: "Asr", sureAdiArapca: "العصر", ayetSayisi: 3 },
  { sira: 104, sureAdi: "Hümeze", sureAdiArapca: "الهمزة", ayetSayisi: 9 },
  { sira: 105, sureAdi: "Fil", sureAdiArapca: "الفيل", ayetSayisi: 5 },
  { sira: 106, sureAdi: "Kureyş", sureAdiArapca: "قريش", ayetSayisi: 4 },
  { sira: 107, sureAdi: "Mâûn", sureAdiArapca: "الماعون", ayetSayisi: 7 },
  { sira: 108, sureAdi: "Kevser", sureAdiArapca: "الكوثر", ayetSayisi: 3 },
  { sira: 109, sureAdi: "Kâfirûn", sureAdiArapca: "الكافرون", ayetSayisi: 6 },
  { sira: 110, sureAdi: "Nasr", sureAdiArapca: "النصر", ayetSayisi: 3 },
  { sira: 111, sureAdi: "Tebbet", sureAdiArapca: "المسد", ayetSayisi: 5 },
  { sira: 112, sureAdi: "İhlâs", sureAdiArapca: "الإخلاص", ayetSayisi: 4 },
  { sira: 113, sureAdi: "Felâk", sureAdiArapca: "الفلق", ayetSayisi: 5 },
  { sira: 114, sureAdi: "Nâs", sureAdiArapca: "الناس", ayetSayisi: 6 },
];

export const FAVORITE_SURE_SIRA = [36, 67, 18, 112];

export const RECENT_SURE_SIRA = [67, 36, 2, 18];

export const LAST_READ = {
  sureAdi: "Mülk",
  ayet: 12,
  sayfa: 562,
};

export const SURE_TABS = [
  { id: "list" as const, label: "Sure Listesi" },
  { id: "recent" as const, label: "Son Okunanlar" },
  { id: "favorites" as const, label: "Favoriler" },
];
